# Generated by Django 5.0 on 2024-03-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updates',
            new_name='updated',
        ),
    ]
